spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # namespace: e13a3310-dd0f-4d64-8d12-6785b0507055
        cluster-name: BJ
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          input:
            destination: add-bonus
            group: binder-group
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      # 抽样率 默认是0.1
      probability: 1

server:
  port: 8030

rocketmq:
  name-server: 127.0.0.1:9876

jwt:
  secret: erudev
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600


